warning: in the working copy of 'apps/client/src/app.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/character_presentation/phase8f_e_tests.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/debug/aoi_view.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/debug/command.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/debug/frame.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/debug/overlay.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/debug/ui_state.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/input.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/lifecycle.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/network/runtime.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/network/state.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/client/src/prediction.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/dev_hub/src/ui/content.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/server/src/network/gameplay.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/server/src/network/handshake.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/server/src/network/replication.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/server/src/network/snapshot.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'apps/server/src/network/tests.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'content/authoring/npcs/welcome/npc.welcome.traveler_stayed.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/common/src/identity.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/common/src/lib.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/content/src/lib.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/content/src/loader.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/content/src/registry.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/src/equipment.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/src/intent.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/src/lib.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/src/message.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/src/snapshot.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/src/version.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/protocol/tests/wire_golden.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/ability.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/collision.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/command.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/debug_action.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/equipment_runtime_behavior_tests.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/footnote/controller.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/footnote/tests.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/lib.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/map_runtime.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/phase47_tests.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/runtime.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'crates/simulation/src/world.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/CONTENT_PIPELINE.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/NPC_AUTHORING_CONTRACT.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/PROTOCOL.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tools/bot_client/src/session.rs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tools/npc_lab/README.md', LF will be replaced by CRLF the next time Git touches it
