use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let content_root = repo.join("content");
    let graphic_root = repo.join("Graphic");
    println!(
        "cargo:rerun-if-changed={}",
        content_root.join("authoring").join("maps").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        content_root.join("shared").join("maps").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        graphic_root.join("assets").join("maps").display()
    );

    let compiled = purgatory_content::compile_registered_map_presentations(&content_root)
        .unwrap_or_else(|error| panic!("PURGATORY map presentation compilation failed:\n{error}"));
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let mut index = String::from("// Generated by apps/client/build.rs. Do not edit.\n");
    index.push_str("static COMPILED_MAPS: &[CompiledMapBytes] = &[\n");
    for map in &compiled {
        let raw = map.content_id.raw().unwrap_or_else(|| {
            panic!(
                "registered map {} has no numeric ContentId",
                map.authored_id
            )
        });
        let presentation_name = format!("map.{raw}.presentation.json");
        let environment_name = format!("map.{raw}.environment.json");
        fs::write(
            output.join(&presentation_name),
            purgatory_content::serialize_map_pretty(&map.presentation)
                .expect("serialize map presentation"),
        )
        .expect("write compiled map presentation");
        fs::write(
            output.join(&environment_name),
            purgatory_content::serialize_map_environment_pretty(&map.environment)
                .expect("serialize map environment presentation"),
        )
        .expect("write compiled map environment presentation");
        for input in &map.inputs {
            println!("cargo:rerun-if-changed={}", input.display());
        }
        for asset in &map.presentation.assets {
            println!(
                "cargo:rerun-if-changed={}",
                graphic_root.join(&asset.source_path).display()
            );
        }
        for layer in map
            .environment
            .parallax_layers
            .iter()
            .chain(map.environment.foreground_layers.iter())
        {
            println!(
                "cargo:rerun-if-changed={}",
                graphic_root.join(&layer.asset_path).display()
            );
        }
        for field in &map.environment.cloud_fields {
            println!(
                "cargo:rerun-if-changed={}",
                graphic_root.join(&field.authored.asset_folder).display()
            );
        }
        index.push_str(&format!(
            "    CompiledMapBytes {{ content_id: {raw}, presentation: include_bytes!(\"{presentation_name}\"), environment: include_bytes!(\"{environment_name}\") }},\n"
        ));
    }
    index.push_str("];\n");
    fs::write(output.join("compiled_map_catalog.rs"), index)
        .expect("write compiled map presentation catalog");
}
