[package]
name = "purgatory-content-validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Validates PURGATORY content definitions."

[[bin]]
name = "purgatory-content-validator"
path = "src/main.rs"

[dependencies]
purgatory-common = { path = "../../crates/common" }
purgatory-content = { path = "../../crates/content" }

[lints]
workspace = true
